spring:
  datasource:
    url: jdbc:mysql://54.208.226.254:3306/FinalProjectDB?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB